/* Return values */ 
#define INITIALIZATION_UNSUCCESSFUL 0
#define INITIALIZATION_SUCCESSFUL 1
#define SOCKET_INITIALIZATION_UNSUCCESSESFUL -1
#define RESIZING_UNSUCCESSFUL -5
#define RESIZING_SUCCESSFUL 5
#define EMPTY -1
#define REMOVED_SUCCESSFULLY 10
#define REMOVED_UNSUCCESSFULLY -10

#define MESSAGE_NOK -420
#define MESSAGE_OK 10
#define MESSAGE_UNKNOWN -1
#define RECONNECTION_OK 1
#define RECONNECTION_ERROR -1
#define PARAMETER_INCORRECT -11
#define EXIT 0
#define PING_OK 1
#define WAITING_PING 0

/* Constants */ 
#define SERVER_PORT 10000
#define LISTEN_BACKLOG 5
#define AMOUNT_OF_PLAYERS 2
#define MAX_SIZE_OF_NAME 10
#define BUFFER_SIZE 124
#define DELIMITER "|"
#define SIZE_OF_BOARD 10
#define RESIZING_CONSTANT 10
#define INITIAL_MAX_OF_GAME_ARRAY 1
#define INITIAL_POSITION_IN_ARRAY 0
#define ANNULL_VALUE 0
#define NO_CIRCLE 0
#define DIRECTIONS 2
#define INVALID_PARAMETER -1
#define PLAYER_NAME 13 /* 12 + '0' */
#define PLAYER_NOT_FOUND 1
#define PLAYER_FOUND -1
#define LOBBY_NAME 11 /* 10 + '0' */
#define MAX_AMOUNT_OF_LOBBIES 10


/* Return values for client */
#define MOVE_OK 200 
#define MOVE_NOK -100
#define VICTORY 201
#define PLAYER1_VICTORY 202 
#define PLAYER2_VICTORY 203
#define DRAW 204
#define LOBBY_JOINED 211
#define LOBBY_CREATED 210
#define LOBBIES_SENT 350
#define RECONNECTION_SUCCESFUL 222
#define MOVE_FROM_OTHER_PLAYER 305
#define DEFEAT -201

#define INVALID_MOVE -400
#define INCORRECT_TURN_MOVE -408
#define ERR_LONG_NAME -410
#define ERR_USER_EXISTS -411
#define ERR_NO_ID -412
#define ERR_X_COORD -413
#define ERR_Y_COORD -414
#define ERR_WRONG_TURN -415
#define ERR_INVALID_MOVE -416
#define ERR_PLAYER_INIT_UNSUCCESSFUL -417
#define UNKNOWN_MESSAGE 500
#define ERR_MAX_LOBBY -450
#define ERR_LOBBY_FULL -451
#define ERR_NO_SUCH_LOBBY -452
#define ERR_LOBBY_NAME -453
#define ERR_LOBBY -454
#define ERR_LOBBY_EXISTS -456
#define ERR_PLAYER_ALREADY_IN_LOBBY -457
#define ERR_USER_NOT_IN_DB -444
#define LOBBY_NOT_FOUND 100
#define ERR_PLAYER_NOT_FOUND -419
#define ERR_INCORRECT_NAME -433
#define ERR_INVALID_NAME -499
#define ERR_PLAYER_TURN -498

#define GAME_START 300

/* State codes */
#define INITIALIZING 0
#define FOUND_FIRST 1
#define FOUND_BOTH 2
#define PLAYER1_TURN 3
#define PLAYER2_TURN 4
#define PLAYER1_DISCONNECTED -1
#define PLAYER2_DISCONNECTED -2
#define GAME_OVER 6

#define DIRECTIONS_LEN 7
#define VICTORY_AMOUNT 1

#define IN_LOBBY 1
#define IN_GAME 2
#define DISCONNECTED 3